# Generated by Django 3.2.16 on 2022-11-04 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gurkul_academic_test_series_model',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('test_class', models.CharField(default='', max_length=10)),
                ('board', models.CharField(default='', max_length=30)),
                ('subject', models.CharField(default='', max_length=30)),
                ('qtype', models.CharField(default='', max_length=50)),
                ('question', models.CharField(default='', max_length=1000)),
                ('acad_q_1', models.CharField(default='', max_length=100)),
                ('acad_q_2', models.CharField(default='', max_length=100)),
                ('acad_q_3', models.CharField(default='', max_length=100)),
                ('acad_q_4', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=5000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
