# Generated by Django 3.2.16 on 2022-11-04 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gurkul_academic_test_series_model',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
