# Generated by Django 4.1.3 on 2022-11-09 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_test', '0002_alter_gurkul_academic_test_series_model_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='gurkul_competition_test_series_model',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=30)),
                ('qtype', models.CharField(default='', max_length=50)),
                ('question', models.CharField(default='', max_length=1000)),
                ('option_1', models.CharField(default='', max_length=100)),
                ('option_2', models.CharField(default='', max_length=100)),
                ('option_3', models.CharField(default='', max_length=100)),
                ('option_4', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=5000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
