# Generated by Django 3.2.16 on 2023-01-18 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_test', '0004_gurkul_academic_test_series_model_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_competition_available_test_series',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(default='', max_length=10)),
                ('subject', models.CharField(default='', max_length=30)),
                ('language', models.CharField(default='Hindi', max_length=30)),
                ('test_type', models.CharField(default='model', max_length=50)),
                ('img', models.ImageField(upload_to='img/gurkul_test/competition_available_test_series')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='all_academic_available_test_series',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('test_class', models.CharField(default='', max_length=10)),
                ('subject', models.CharField(default='', max_length=30)),
                ('language', models.CharField(default='Hindi', max_length=30)),
                ('board', models.CharField(default='', max_length=30)),
                ('test_type', models.CharField(default='model', max_length=50)),
                ('img', models.ImageField(upload_to='img/gurkul_test/academic_available_test_series')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
