# Generated by Django 3.2.16 on 2023-03-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_test', '0005_all_academic_available_test_series_all_competition_available_test_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='gta_all_question',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(default='GTA00', max_length=15)),
                ('question_category', models.CharField(choices=[('Acad', 'Academic'), ('Other', 'Other')], default='Other', max_length=20)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('Other', 'Other')], default='Other', max_length=30)),
                ('board', models.CharField(choices=[('UPBoard', 'UP Board'), ('Other', 'Other')], default='Other', max_length=50)),
                ('standard', models.CharField(choices=[('12', '12th'), ('Other', 'Other')], default='Other', max_length=50)),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Other', 'Other')], default='Other', max_length=30)),
                ('qtype', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('Other', 'Other')], default='Other', max_length=50)),
                ('question', models.TextField()),
                ('option_1', models.CharField(default='', max_length=100)),
                ('option_2', models.CharField(default='', max_length=100)),
                ('option_3', models.CharField(default='', max_length=100)),
                ('option_4', models.CharField(default='', max_length=100)),
                ('answer', models.TextField(default='', max_length=5000)),
                ('answer_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('Other', 'Other')], default='Other', max_length=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
