# Generated by Django 3.2.16 on 2023-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0006_gta_all_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gta_all_question',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('STQ', 'Short Type Question'), ('LTQ', 'Long Type Question'), ('VLTQ', 'Very Long Type Question'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='question_category',
            field=models.CharField(choices=[('Acad', 'Academic'), ('Comp', 'Competition'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='standard',
            field=models.CharField(choices=[('10', '10th'), ('11', '11th'), ('12', '12th'), ('NEET', 'National Eligibility cum Entrance Test (NEET)'), ('SSC', 'Staff Selection Commission'), ('Banking', 'Banking'), ('UPP/UPSI', 'UPP/UP Police SI'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Geography', 'Geography'), ('Reasoning', 'Reasoning'), ('GS/GK', 'General Science (GS) / General Knowledge (GK)'), ('History', 'History'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
