# Generated by Django 4.1.7 on 2023-03-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0009_alter_gta_all_question_qtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gta_all_question',
            name='question_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/questions/%y/%m/%d'),
        ),
    ]
