# Generated by Django 4.1.7 on 2023-03-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0010_gta_all_question_question_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gta_all_question',
            name='question_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/%y/%m/%d/answer'),
        ),
    ]
