# Generated by Django 4.1.7 on 2023-03-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0011_alter_gta_all_question_question_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='gta_all_question',
            name='answer_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/%y/%m/%d/answer'),
        ),
        migrations.AddField(
            model_name='gta_all_question',
            name='option_1_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/%y/%m/%d/option_1'),
        ),
        migrations.AddField(
            model_name='gta_all_question',
            name='option_2_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/%y/%m/%d/option_2'),
        ),
        migrations.AddField(
            model_name='gta_all_question',
            name='option_3_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/%y/%m/%d/option_3'),
        ),
        migrations.AddField(
            model_name='gta_all_question',
            name='option_4_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/%y/%m/%d/option_4'),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='question_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/%y/%m/%d/question'),
        ),
    ]
