# Generated by Django 4.1.7 on 2023-04-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0012_gta_all_question_answer_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gurkul_competition_test_series_model',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='gurkul_academic_test_series_model',
        ),
        migrations.DeleteModel(
            name='gurkul_competition_test_series_model',
        ),
    ]
