# Generated by Django 4.1.7 on 2023-04-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0013_remove_gurkul_competition_test_series_model_user_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gta_test_series',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(default='', max_length=15)),
                ('category', models.CharField(default='', max_length=20)),
                ('language', models.CharField(default='', max_length=20)),
                ('board', models.CharField(default='', max_length=20)),
                ('standard', models.CharField(default='', max_length=20)),
                ('subject', models.CharField(default='', max_length=20)),
                ('qtype', models.CharField(default='', max_length=7)),
                ('length', models.IntegerField()),
                ('banner', models.ImageField(default='', upload_to='img/gurkul_test/all_gta_test_modals/year_%Y/month_%m/day_%d/answer')),
            ],
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='answer_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/year_%Y/month_%m/day_%d/answer'),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='option_1_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/year_%Y/month_%m/day_%d/option_1'),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='option_2_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/year_%Y/month_%m/day_%d/option_2'),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='option_3_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/year_%Y/month_%m/day_%d/option_3'),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='option_4_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/year_%Y/month_%m/day_%d/option_4'),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='question_img',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_questions/year_%Y/month_%m/day_%d/question'),
        ),
    ]
