# Generated by Django 4.1.7 on 2023-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0014_gta_test_series_alter_gta_all_question_answer_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gta_test_series',
            name='banner',
            field=models.ImageField(default='', upload_to='img/gurkul_test/all_gta_test_modals/banners'),
        ),
    ]
