# Generated by Django 4.1.7 on 2023-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0015_alter_gta_test_series_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gta_test_series',
            name='category',
        ),
        migrations.AddField(
            model_name='gta_test_series',
            name='question_category',
            field=models.CharField(choices=[('Acad', 'Academic'), ('Comp', 'Competition'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='gta_test_series',
            name='board',
            field=models.CharField(choices=[('UPBoard', 'UP Board'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='gta_test_series',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='gta_test_series',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question (MCQ)'), ('STQ', 'Short Type Question (STQ)'), ('LTQ', 'Long Type Question (LTQ)'), ('VLTQ', 'Very Long Type Question (VLTQ)'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='gta_test_series',
            name='standard',
            field=models.CharField(choices=[('10', '10th'), ('11', '11th'), ('12', '12th'), ('NEET', 'National Eligibility cum Entrance Test (NEET)'), ('SSC', 'Staff Selection Commission'), ('Banking', 'Banking'), ('UPP/UPSI', 'UPP/UP Police SI'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='gta_test_series',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Geography', 'Geography'), ('Reasoning', 'Reasoning'), ('GS/GK', 'General Science (GS) / General Knowledge (GK)'), ('History', 'History'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
