# Generated by Django 4.1.7 on 2023-04-30 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0016_remove_gta_test_series_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gta_test_series',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
