# Generated by Django 4.1.7 on 2023-05-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0017_gta_test_series_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gta_all_question',
            name='standard',
            field=models.CharField(choices=[('10', '10th'), ('11', '11th'), ('12', '12th'), ('NEET', 'National Eligibility cum Entrance Test (NEET)'), ('SSC', 'Staff Selection Commission'), ('Banking', 'Banking'), ('UPPorUPSI', 'UPP/UP Police SI'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='gta_all_question',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Geography', 'Geography'), ('Reasoning', 'Reasoning'), ('GSorGK', 'General Science (GS) / General Knowledge (GK)'), ('History', 'History'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='gta_test_series',
            name='standard',
            field=models.CharField(choices=[('10', '10th'), ('11', '11th'), ('12', '12th'), ('NEET', 'National Eligibility cum Entrance Test (NEET)'), ('SSC', 'Staff Selection Commission'), ('Banking', 'Banking'), ('UPPorUPSI', 'UPP/UP Police SI'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='gta_test_series',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Geography', 'Geography'), ('Reasoning', 'Reasoning'), ('GSorGK', 'General Science (GS) / General Knowledge (GK)'), ('History', 'History'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
