# Generated by Django 4.1.7 on 2023-05-05 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0018_alter_gta_all_question_standard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gta_test_series',
            old_name='time',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='gta_test_series',
            old_name='length',
            new_name='questions_length',
        ),
        migrations.AddField(
            model_name='gta_test_series',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='gta_test_series',
            name='total_length',
            field=models.IntegerField(default=30),
        ),
    ]
