# Generated by Django 4.1.7 on 2023-05-17 08:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0020_gta_test_series_negative_marking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gta_test_series',
            name='negative_marking',
            field=models.DecimalField(choices=[(Decimal('-0.50'), '-1/2 Markin per wrong answer'), (Decimal('-1.00'), '-1 Markin per wrong answer'), (Decimal('-1.50'), '-3/2 Markin per wrong answer'), (Decimal('-2.00'), '-2 Markin per wrong answer')], decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gta_test_series',
            name='positive_marking',
            field=models.DecimalField(choices=[(Decimal('0.50'), '1/2 Markin per right answer'), (Decimal('1.00'), '1 Markin per right answer'), (Decimal('1.50'), '3/2 Markin per right answer'), (Decimal('2.00'), '2 Markin per right answer'), (Decimal('2.50'), '5/2 Markin per right answer'), (Decimal('3.00'), '3 Markin per right answer')], decimal_places=2, max_digits=5),
        ),
    ]
