# Generated by Django 4.1.7 on 2023-05-24 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0021_alter_gta_test_series_negative_marking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gta_test_series',
            name='reading_time',
            field=models.DurationField(choices=[(datetime.timedelta(0), '0 Minutes'), (datetime.timedelta(seconds=300), '5 Minutes'), (datetime.timedelta(seconds=600), '10 Minutes'), (datetime.timedelta(seconds=900), '15 Minutes')], default=datetime.timedelta(seconds=1800)),
        ),
    ]
