# Generated by Django 3.2.19 on 2023-06-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_test', '0023_alter_gta_test_series_negative_marking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gta_all_question',
            name='standard',
            field=models.CharField(choices=[('10', '10th'), ('11', '11th'), ('12', '12th'), ('NEET', 'National Eligibility cum Entrance Test (NEET)'), ('SSC', 'Staff Selection Commission'), ('Banking', 'Banking'), ('UPPorUPSI', 'UPP/UP Police SI'), ('TET', 'Teacher Eligibility Test (TET)'), ('CTET', 'Central Teacher Eligibility Test (CTET)'), ('STET', 'Secondary Teacher Eligibility Test (STET)'), ('PET', 'Preliminary Eligibility Test (PET)'), ('SSC_GD', 'Staff Selection Commision (SSC GD)'), ('SSC_MTS', 'Staff Selection Commision (SSC MTS)'), ('SSC_CGL', 'Staff Selection Commision (SSC CGL)'), ('PCS', 'Provincial Civil Service (PCS)'), ('UPSC', 'Union Public Service Commission (UPSC)'), ('PRT', 'Primary teacher (PRT)'), ('KVS', 'Kendriya Vidyalaya Sangathan (KVS)'), ('TGT', 'Trained Graduate Teacher (TGT)'), ('PGT', 'Post-Graduate Teacher (PGT)'), ('NET', 'National Eligibility Test (NET)'), ('GATE', 'Graduate Aptitude Test in Engineering (GATE)'), ('UPSSSC', 'Uttar Pradesh Subordinate Services Selection Commission (UPSSSC)'), ('NDA', 'National Defence Academy (NDA)'), ('Air_Force', 'Air Force'), ('Navy', 'Navy'), ('Navy_SSR', 'Indian Navy Senior Secondary Recruit (Navy SSR)'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='gta_test_series',
            name='standard',
            field=models.CharField(choices=[('10', '10th'), ('11', '11th'), ('12', '12th'), ('NEET', 'National Eligibility cum Entrance Test (NEET)'), ('SSC', 'Staff Selection Commission'), ('Banking', 'Banking'), ('UPPorUPSI', 'UPP/UP Police SI'), ('TET', 'Teacher Eligibility Test (TET)'), ('CTET', 'Central Teacher Eligibility Test (CTET)'), ('STET', 'Secondary Teacher Eligibility Test (STET)'), ('PET', 'Preliminary Eligibility Test (PET)'), ('SSC_GD', 'Staff Selection Commision (SSC GD)'), ('SSC_MTS', 'Staff Selection Commision (SSC MTS)'), ('SSC_CGL', 'Staff Selection Commision (SSC CGL)'), ('PCS', 'Provincial Civil Service (PCS)'), ('UPSC', 'Union Public Service Commission (UPSC)'), ('PRT', 'Primary teacher (PRT)'), ('KVS', 'Kendriya Vidyalaya Sangathan (KVS)'), ('TGT', 'Trained Graduate Teacher (TGT)'), ('PGT', 'Post-Graduate Teacher (PGT)'), ('NET', 'National Eligibility Test (NET)'), ('GATE', 'Graduate Aptitude Test in Engineering (GATE)'), ('UPSSSC', 'Uttar Pradesh Subordinate Services Selection Commission (UPSSSC)'), ('NDA', 'National Defence Academy (NDA)'), ('Air_Force', 'Air Force'), ('Navy', 'Navy'), ('Navy_SSR', 'Indian Navy Senior Secondary Recruit (Navy SSR)'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
