# Generated by Django 3.2.13 on 2022-10-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gurkul_all_student',
        ),
    ]
