# Generated by Django 3.2.16 on 2023-01-16 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_student', '0002_delete_gurkul_all_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_profile_data',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(default='', max_length=20)),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('mob', models.CharField(default='', max_length=20)),
                ('wmob', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('zip', models.CharField(default='', max_length=100)),
                ('bio', models.CharField(default='', max_length=1000)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
