# Generated by Django 3.2.16 on 2023-01-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_student', '0003_student_profile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile_data',
            name='father_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student_profile_data',
            name='mother_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student_profile_data',
            name='pmob',
            field=models.CharField(default='', max_length=20),
        ),
    ]
