# Generated by Django 3.2.16 on 2023-03-05 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_student', '0004_auto_20230118_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_educational_profile_data',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(default='', max_length=20)),
                ('data_field', models.IntegerField()),
                ('standard', models.CharField(default='', max_length=20)),
                ('stream', models.CharField(default='', max_length=20)),
                ('college', models.CharField(default='', max_length=100)),
                ('board', models.CharField(default='', max_length=100)),
                ('roll_no', models.CharField(default='', max_length=20)),
                ('maximum_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('marks_percent', models.CharField(default='', max_length=10)),
                ('year', models.CharField(default='', max_length=10)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
