# Generated by Django 4.1.7 on 2023-05-02 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_student', '0005_student_educational_profile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_educational_profile_data',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student_profile_data',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='student_test_paper_data',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.CharField(default='', max_length=20)),
                ('attempt', models.IntegerField(default=0)),
                ('attempt_status', models.CharField(choices=[('Yes', 'Completed'), ('No', 'Not Completed')], default='No', max_length=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
