# Generated by Django 3.2.13 on 2022-10-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gurkul_teacher', '0002_delete_gurkul_all_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_auth',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(default='', max_length=20)),
                ('edit_test_series', models.BooleanField()),
            ],
        ),
    ]
