# Generated by Django 3.2.13 on 2022-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_teacher', '0003_teacher_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_auth',
            name='edit_test_series',
            field=models.BooleanField(default=False),
        ),
    ]
