# Generated by Django 3.2.13 on 2022-11-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_teacher', '0004_alter_teacher_auth_edit_test_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_auth',
            name='teacher_username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
