# Generated by Django 3.2.13 on 2022-11-02 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_teacher', '0005_teacher_auth_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_auth',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
