# Generated by Django 3.2.16 on 2023-01-07 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_teacher', '0006_teacher_auth_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_profile_data',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(default='', max_length=20)),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('mob', models.CharField(default='', max_length=20)),
                ('wmob', models.CharField(default='', max_length=20)),
                ('subject', models.CharField(default='', max_length=40)),
                ('address', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('zip', models.CharField(default='', max_length=100)),
                ('bio', models.CharField(default='', max_length=1000)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
