# Generated by Django 4.1.7 on 2023-03-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_teacher', '0007_teacher_profile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_auth',
            name='send_request_esdit_test_series',
            field=models.CharField(choices=[('none', 'Do Not Send The Request'), ('send', 'Send Request'), ('accept', 'Request Accepted'), ('decline', 'Request Declined')], default='none', max_length=30),
        ),
    ]
