# Generated by Django 4.2.7 on 2023-11-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_teacher', '0009_rename_send_request_esdit_test_series_teacher_auth_send_request_edit_test_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_auth',
            name='send_request_edit_sms_exam_student_data',
            field=models.CharField(choices=[('none', 'Do Not Send The Request'), ('send', 'Send Request'), ('accept', 'Request Accepted'), ('decline', 'Request Declined')], default='none', max_length=30),
        ),
    ]
