# Generated by Django 4.2.7 on 2023-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_teacher', '0010_teacher_auth_send_request_edit_sms_exam_student_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_auth',
            name='send_request_edit_sms_exam_student_data',
        ),
        migrations.AddField(
            model_name='teacher_auth',
            name='edit_sms_exam_student_data',
            field=models.BooleanField(default=False),
        ),
    ]
