# Generated by Django 3.2.13 on 2022-10-17 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='landing_home_page_slide',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(upload_to='img/the_gurkul/home/landing_home_page_slide')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_faculty',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('about', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='img/the_gurkul/home/teacher_faculty')),
            ],
        ),
    ]
