# Generated by Django 3.2.13 on 2022-10-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing_home_page_slide',
            name='img',
            field=models.ImageField(upload_to='img/gurkul_admin/home/landing_home_page_slide'),
        ),
        migrations.AlterField(
            model_name='teacher_faculty',
            name='img',
            field=models.ImageField(upload_to='img/gurkul_admin/home/teacher_faculty'),
        ),
    ]
