# Generated by Django 3.2.13 on 2022-10-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_admin', '0004_all_usrs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users_registration',
        ),
    ]
