# Generated by Django 3.2.13 on 2022-10-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_admin', '0005_delete_users_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_usrs',
            old_name='user_id',
            new_name='student_id',
        ),
    ]
