# Generated by Django 3.2.13 on 2022-10-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_admin', '0006_rename_user_id_all_usrs_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_usrs',
            name='passwd',
            field=models.CharField(default='', max_length=100),
        ),
    ]
