# Generated by Django 3.2.16 on 2022-12-31 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_admin', '0008_gurkul_all_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('visitor_type', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='vistor_count',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='', max_length=30)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='teacher_faculty',
            name='quote',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
