# Generated by Django 3.2.16 on 2023-01-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_admin', '0009_auto_20221231_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='captcha_data',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('first_character', models.CharField(default='', max_length=1)),
                ('second_character', models.CharField(default='', max_length=1)),
                ('value', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
