# Generated by Django 3.2.16 on 2023-01-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_admin', '0010_captcha_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gurkul_all_superuser',
            old_name='user_type',
            new_name='visitor_type',
        ),
    ]
