# Generated by Django 4.1.2 on 2022-10-21 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_profile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=20)),
                ('branch_mgr', models.CharField(default='', max_length=50)),
                ('branch_mgr_mob', models.BigIntegerField(default=0)),
                ('branch_add', models.CharField(max_length=200)),
                ('reg_date', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
