# Generated by Django 4.1.2 on 2022-10-22 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_branch', '0002_branch_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_profile',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='branch_teacher_faculty',
            name='join_time',
        ),
        migrations.AddField(
            model_name='branch_profile',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='branch_teacher_faculty',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
