# Generated by Django 3.2.13 on 2022-10-29 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gurkul_branch', '0003_remove_branch_profile_reg_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gurkul_all_branch',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('passwd', models.CharField(default='', max_length=100)),
                ('branch_id', models.CharField(default='', max_length=20, null=True)),
                ('user_type', models.CharField(max_length=40)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
