# Generated by Django 3.2.13 on 2022-10-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gurkul_branch', '0004_gurkul_all_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gurkul_all_branch',
        ),
    ]
