# Generated by Django 4.2.5 on 2023-10-17 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentRegistration',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('uin_no', models.CharField(default='GTASMS0', max_length=11)),
                ('img', models.ImageField(upload_to='img/smsExam/%Y/%m')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mob', models.CharField(default='', max_length=20)),
                ('wmob', models.CharField(default='', max_length=20)),
                ('father_name', models.CharField(default='', max_length=50)),
                ('mother_name', models.CharField(default='', max_length=50)),
                ('dob', models.DateField(default='2000-01-01')),
                ('aadhar', models.CharField(default='0000 0000 0000', max_length=13)),
                ('std_class', models.CharField(choices=[('10', 'Ten (10th)'), ('9', 'Nine (9th)'), ('11', 'Eleven (11th)'), ('12', 'Twelve (12th)'), ('Other', 'Other')], default='Other', max_length=10)),
                ('subject_class', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Other', 'Other')], default='Other', max_length=20)),
                ('institution', models.CharField(default='The Gurkul', max_length=100)),
                ('addr', models.CharField(default='Bahraich', max_length=100)),
                ('time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
