# Generated by Django 4.2.7 on 2023-11-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsExam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='std_class',
            field=models.CharField(choices=[('Other', 'Other'), ('11', 'Eleven (11th)'), ('12', 'Twelve (12th)'), ('9', 'Nine (9th)'), ('10', 'Ten (10th)')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='subject_class',
            field=models.CharField(choices=[('Other', 'Other'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology')], default='Other', max_length=20),
        ),
    ]
