# Generated by Django 4.2.7 on 2023-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsExam', '0002_alter_studentregistration_std_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='std_class',
            field=models.CharField(choices=[('9', 'Nine (9th)'), ('12', 'Twelve (12th)'), ('10', 'Ten (10th)'), ('Other', 'Other'), ('11', 'Eleven (11th)')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='subject_class',
            field=models.CharField(choices=[('Other', 'Other'), ('Biology', 'Biology'), ('Mathematics', 'Mathematics')], default='Other', max_length=20),
        ),
    ]
